### ISSUE TITLE
Use Cobra to increase codebase "conventionality"

### ISSUE THREAD

**Issue by skmgoldin** [INFURA/eth2-comply#10]
I do not know too much about Cobra, other than that is a very popular tool for building CLI applications in Go. I also believe I understand that Cobra is somewhat opinionated about how applications built using Cobra should be structured.

While I don't think my code is _too_ hairy, I also don't think it's very conventional. Conventionality for its own sake is worthwhile, IMO, for improving the ability to reason about codebases more easily, onboard new developers, etc.

In the course of doing a Cobra refactor, a good "test" for whether the refactor is worthwhile and healthy should be whether the code that comes out on the other side is itself testable. eth2-comply, a testing tool, does not have any tests of it own. To close this issue I would want to see that the state of test coverage in the repo either is improved or can be improved as a result of the refactor.

**Comment by MichaelMure** [comment]
Cobra is nice but does encourage you to just use a bunch of global variables everywhere (meaning, hard to test). I'd very much advise you to structure your commands in a similar fashion as https://github.com/MichaelMure/git-bug/tree/master/commands

**Comment by sprrtely** [comment]
Closing per Mike Goldin's comment:
> _backlog, probably graveyard_
